name: Update data

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs weekly at midnight UTC on Sunday. Adjust as needed.
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  

      - name: Install Python packages
        run: |
          pip install requests
          pip install pyodbc
          pip install pandas


      - name: List files in directory (optional for debugging)
        run: |
          ls  # List files in the current directory

      - name: Run Python script
        run: |
          python crypto_metadata.py
      - name: Run Python script
        run: |
          python exchange_metadata.py
